# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  repositories:
    - repository: inventory
      type: github
      name: JamesJonesConsulting/AnsibleInventory
      endpoint: JamesJonesConsulting      
    - repository: vault
      type: github
      name: JamesJonesConsulting/AnsibleVault
      endpoint: JamesJonesConsulting      
  containers: 
    - container: podman-dind
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      endpoint: JamesJonesConsultingDockerNexusHosted
      options: --userns=keep-id --privileged --user root
pool: FedoraHosted
container: podman-dind
variables:
  - group: Connections
  - name: ARTIFACTORY_HOST
    value: nexus.jamesjonesconsulting.com

steps:
  - checkout: self 
    path: s/pipeline
  - checkout: inventory
    path: s/inventory
  - checkout: vault
    path: s/vault

  - bash: |
      eval $(ssh-agent); ssh-add <(echo "${SSH_KEY}" | base64 -d);
      echo -n "${VAULT_KEY}" | base64 -d > $(Agent.TempDirectory)/.vault
    workingDirectory: $(Build.SourcesDirectory)/pipeline
    displayName: Connect to host and setup Azure DevOps agent with Podman
    env:
      SSH_KEY: $(default_ssh_key)
      VAULT_KEY: $(ansible_vault_key)
  - bash: |
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install --upgrade pip setuptools wheel "cython<3.0.0"

      python3 -m pip install .

      python3 build.py

      # Branch detection
      GITREF=$(git symbolic-ref HEAD)

      if [[ "$GITREF" =~ ^refs/tags.* ]]; then
        VERSION=$(git symbolic-ref --short HEAD)
      else
        VERSION=$(dist/voterwarehouse -v)
        VERSION+="~"
        VERSION+=$(git symbolic-ref --short HEAD | sed 's|/|-|g')
      fi
    workingDirectory: $(Build.SourcesDirectory)/pipeline
    displayName: Build Python Package
  - bash: |
      if [[ "$BUILD_SOURCEBRANCH" == refs/tags/* ]]; then
        tag="${BUILD_SOURCEBRANCH#refs/tags/}"

        echo "Tag: $tag"
        echo "##vso[task.setvariable variable=gitRefType]tag"
        echo "##vso[task.setvariable variable=gitRefName]$tag"
      else
        branch="${BUILD_SOURCEBRANCH#refs/heads/}"

        # Replace "/" with "-"
        branch="${branch//\//-}"

        # Get the application version
        version="$(dist/voterwarehouse -v)"

        # Prepend the version and "~" to the branch name
        refName="${version}~${branch}"

        echo "Branch: $refName"
        echo "##vso[task.setvariable variable=gitRefType]branch"
        echo "##vso[task.setvariable variable=gitRefName]$refName"
      fi
    displayName: Get version and normalized tag or branch name
    workingDirectory: $(Build.SourcesDirectory)/pipeline
  - bash: |
      echo "Reference type: $(gitRefType)"
      echo "Reference name: $(gitRefName)"
      fpm -s dir -t rpm -n voterwarehouse -v $(gitRefName) --iteration $(Build.BuildNumber) \
        --description "VoterWarehouse: Imports and Extracts Voter and History data" \
        --url "https://github.com/jamjon3/VoterWarehouse" \
        --license "LGPL3.0" --vendor "James Jones" \
        --config-files /etc/VoterWarehouse/config.yml \
        -p ./dist \
        ./dist/voterwarehouse=/usr/bin/voterwarehouse \
        ./config.sample.yml=/etc/VoterWarehouse/config.yml
    displayName: Build the RPM package
    workingDirectory: $(Build.SourcesDirectory)/pipeline
