# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  repositories:
    - repository: inventory
      type: github
      name: JamesJonesConsulting/AnsibleInventory
      endpoint: JamesJonesConsulting      
    - repository: vault
      type: github
      name: JamesJonesConsulting/AnsibleVault
      endpoint: JamesJonesConsulting      
  containers: 
    - container: podman-dind
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      endpoint: JamesJonesConsultingDockerNexusHosted
      options: --userns=keep-id --privileged --user root

pool: FedoraHosted
container: podman-dind
variables:
  - group: Connections

steps:
  - checkout: self 
    path: s/pipeline
  - checkout: inventory
    path: s/inventory
  - checkout: vault
    path: s/vault

  - bash: |
      eval $(ssh-agent); ssh-add <(echo "${SSH_KEY}" | base64 -d);
      echo -n "${VAULT_KEY}" | base64 -d > $(Agent.TempDirectory)/.vault
    workingDirectory: $(Build.SourcesDirectory)/pipeline
    displayName: Connect to host and setup Azure DevOps agent with Podman
    env:
      SSH_KEY: $(default_ssh_key)
      VAULT_KEY: $(ansible_vault_key)

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
