# -*- coding: utf-8 -*-

__history_import_map__ = {
    "county_code": [],
    "voter_id": [],
    "election_date": [],
    "election_type": [],
    "history_code": []
}

__voter_import_map__ = {
    "county_code": [],
    "voter_id": [],
    "name_last": [],
    "name_suffix": [],
    "name_first": [],
    "name_middle": [],
    "suppress_address": [],
    "residence_address_line_1": [],
    "residence_address_line_2": [],
    "residence_city": [],
    "residence_state": [],
    "residence_zipcode": [],
    "mailing_address_line_1": [],
    "mailing_address_line_2": [],
    "mailing_address_line_3": [],
    "mailing_city": [],
    "mailing_state": [],
    "mailing_zipcode": [],
    "mailing_country": [],
    "gender": [],
    "race": [],
    "birth_date": [],
    "registration_date": [],
    "party_affiliation": [],
    "precinct": [],
    "precinct_group": [],
    "precinct_split": [],
    "precinct_suffix": [],
    "voter_status": [],
    "congressional_district": [],
    "house_district": [],
    "senate_district": [],
    "county_commission_district": [],
    "school_board_district": [],
    "daytime_area_code": [],
    "daytime_phone_number": [],
    "daytime_phone_extension": [],
    "email_address": []
}

__suppress_keys__ = [
    "name_last",
    "name_suffix",
    "name_first",
    "name_middle",
    "residence_address_line_1",
    "residence_address_line_2",
    "residence_city",
    "residence_state",
    "residence_zipcode",
    "mailing_address_line_1",
    "mailing_address_line_2",
    "mailing_address_line_3",
    "mailing_city",
    "mailing_state",
    "mailing_zipcode",
    "mailing_country",
    "precinct",
    "precinct_group",
    "precinct_split",
    "precinct_suffix",
    "congressional_district",
    "house_district",
    "senate_district",
    "county_commission_district",
    "school_board_district",
    "daytime_area_code",
    "daytime_phone_number",
    "daytime_phone_extension",
    "email_address"
]
