name: Build VoterWarehouse
on: push

jobs:
  build-job:
    runs-on: self-hosted
    container:
      image: registry.fedoraproject.org/fedora:latest
      options: --userns=keep-id --privileged --user root
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Sets up RPM build tools and Ruby Gems
      - name: Install RPM dependencies
        run: |
          dnf install -y rpm-build rpm-sign rubygems ruby-devel gcc gcc-c++ make \
            libffi-devel python3 python3-pip python3-virtualenv curl pinentry
      # Sets up Rubygems packaging pinentry-program /usr/bin/pinentry-curses
      - name: Setup FPM with it's dependent package for building a package
        run: |
          gem install ffi
          gem install fpm
          gem install package_cloud
          echo $PC_TOKEN | base64 -d > ~/.packagecloud
        env:
          PC_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      # Sets up the python virtual environment, pulls the requirements and builds the binary
      - name: Build the binary
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install -r requirements.txt
          python build.py
      - name: Build the RPM package
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags.* ]]; then
            VERSION=$GITHUB_REF_NAME
          else
            VERSION=$(./dist/voterwarehouse -v)
            VERSION+=$(echo "~${GITHUB_REF_NAME}" | sed 's|/|-|g')
          fi
          echo "$VERSION"
          echo "$GITHUB_RUN_NUMBER"
          fpm -s dir -t rpm -n voterwarehouse -v ${VERSION} --iteration ${GITHUB_RUN_NUMBER} \
          --description "VoterWarehouse: Imports and Extracts Voter and History data" \
          --url "https://github.com/jamjon3/VoterWarehouse" \
          --license "LGPL-3.0" --vendor "James Jones" \
          --config-files /etc/VoterWarehouse/config.yml \
          -p ./dist \
          ./dist/voterwarehouse=/usr/bin/voterwarehouse \
          ./config.sample.yml=/etc/VoterWarehouse/config.yml
          PACKAGE_FILE=$(find . -type f -name "voterwarehouse*.rpm")
          rpm --import https://nexus.jamjon3.sytes.net/repository/gpg/RPM-GPG-KEY-JAMJON3
          echo "${{ secrets.JAMJON3_RPM_SIGN_GPG_KEY }}" | base64 -d > key.gpg
          echo "${{ secrets.JAMJON3_RPM_SIGN_GPG_SECRET_KEY }}" | base64 -d > private.gpg
          ls -all *.gpg
          export GPG_TTY=$(tty)
          gpg --import key.gpg
          echo '${{ secrets.JAMJON3_RPM_SIGN_PASSPHRASE }}' | gpg --batch --import private.gpg
          rpm --define "_gpg_name James Jones <jamjon3@gmail.com>" \
            --define "_gpg_sign_cmd_extra_args --pinentry-mode loopback --passphrase ${{ secrets.JAMJON3_RPM_SIGN_PASSPHRASE }}" \
            --addsign $PACKAGE_FILE
          curl -v -u "$YUM_USER:$YUM_PASSWORD" --upload-file $PACKAGE_FILE $NEXUS_YUM_REPO
          # package_cloud push $PACKAGE_CLOUD_REPO $PACKAGE_FILE
        shell: bash
        env:
          PACKAGE_CLOUD_REPO: jamjon3/yum/rpm_any/rpm_any
          YUM_USER: ${{ secrets.HOME_NEXUS_YUM_USER }}
          YUM_PASSWORD: ${{ secrets.HOME_NEXUS_YUM_PASSWORD }}
          NEXUS_YUM_REPO: https://nexus.jamjon3.sytes.net/repository/yum-hosted/voting/
      - name: Build the DEB package
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags.* ]]; then
            VERSION=$GITHUB_REF_NAME
          else
            VERSION=$(./dist/voterwarehouse -v)
            VERSION+=$(echo "~${GITHUB_REF_NAME}" | sed 's|/|-|g')
          fi
          echo "$VERSION"
          echo "$GITHUB_RUN_NUMBER"
          fpm -s dir -t deb -n voterwarehouse -v ${VERSION} --iteration ${GITHUB_RUN_NUMBER} \
          --description "VoterWarehouse: Imports and Extracts Voter and History data" \
          --url "https://github.com/jamjon3/VoterWarehouse" \
          --license "LGPL-3.0" --vendor "James Jones" \
          --config-files /etc/VoterWarehouse/config.yml \
          -p ./dist \
          ./dist/voterwarehouse=/usr/bin/voterwarehouse \
          ./config.sample.yml=/etc/VoterWarehouse/config.yml
          PACKAGE_FILE=$(find . -type f -name "voterwarehouse*.deb")
          # package_cloud push $PACKAGE_CLOUD_REPO $PACKAGE_FILE
          # curl -v -u '${YUM_USER}:${YUM_PASSWORD}' --upload-file $PACKAGE_FILE $NEXUS_YUM_REPO
        shell: bash
        env:
          PACKAGE_CLOUD_REPO: jamjon3/deb/any/any
          YUM_USER: ${{ secrets.HOME_NEXUS_YUM_USER }}
          YUM_PASSWORD: ${{ secrets.HOME_NEXUS_YUM_PASSWORD }}
          NEXUS_YUM_REPO: https://nexus.jamjon3.sytes.net/repository/yum-hosted/
    
