name: Build VoterWarehouse and publish artifacts
on: push
env:
  registry-proxy: nexus.jamesjonesconsulting.com:5444
  binary-basename: voterwarehouse
  python-win-version: 3.11.3
jobs:
  build-publish-job:
    name: Building and publishing artifacts
    runs-on: self-hosted
    container:
      image: nexus.jamesjonesconsulting.com:5444/podman/stable:latest
      options: --userns=keep-id --privileged --user root
      # options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    steps:
      # Sets up RPM build tools and Ruby Gems
      - name: Install RPM dependencies
        run: |
          dnf install -y rpm-build rpm-sign rubygems ruby-devel gcc gcc-c++ make podman-docker \
            libffi-devel python3 python3-pip python3-virtualenv python3-wheel upx wget curl pinentry \
            dotnet-sdk-7.0
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.registry-proxy }}
          username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
          password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
      # Sets up Rubygems packaging pinentry-program /usr/bin/pinentry-curses
      - name: Setup FPM with it's dependent package for building a package
        run: |
          gem install ffi
          gem install fpm
          gem install package_cloud
          echo $PC_TOKEN | base64 -d > ~/.packagecloud
        env:
          PC_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      # Sets up the python virtual environment, pulls the requirements and builds the binary
      - name: Build the Linux and Windows binaries
        run: |
          podman build --no-cache \
            --build-arg PYTHON_VERSION=${{ env.python-win-version }} \
            --build-arg ARTIFACTORY=${{ env.registry-proxy }} \
            -f Dockerfile.centos7 \
            -v "$(pwd):/work:Z" .
          podman build --no-cache \
            --build-arg PYTHON_VERSION=${{ env.python-win-version }} \
            --build-arg ARTIFACTORY=${{ env.registry-proxy }} \
            -f Dockerfile.wine.python \
            -v "$(pwd):/work:Z" .
      - name: Generate Versions
        id: package-versions
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags.* ]]; then
            echo "standard=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
            echo "rpm=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
            DEB_VER=$(echo "$GITHUB_REF_NAME" | sed 's|_|-|g')
            echo "deb=$DEB_VER" >> $GITHUB_OUTPUT
            echo "nuget=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          else
            VERSION=$(./dist/${{ env.binary-basename }} -v)
            NUGET_VERSION="$VERSION"
            VERSION+=$(echo "~${GITHUB_REF_NAME}" | sed "s|/${VERSION}||g" | sed 's|/|-|g')
            echo "standard=$VERSION" >> $GITHUB_OUTPUT
            echo "rpm=$VERSION" >> $GITHUB_OUTPUT
            DEB_VER=$(echo "$VERSION" | sed 's|_|-|g')
            echo "deb=$DEB_VER" >> $GITHUB_OUTPUT
            NUGET_VERSION+=$(echo "-${GITHUB_REF_NAME}" | sed "s|/${NUGET_VERSION}||g" | sed 's|/|-|g')
            echo "nuget=$NUGET_VERSION" >> $GITHUB_OUTPUT
          fi
#      - name: Build the Windows binary
#        uses: "./.github/actions/wine-build"
#        with:
#          binary-basename: ${{ env.binary-basename }}
#          version: ${{ steps.package-versions.outputs.standard }}
#          registry-proxy: ${{ env.registry-proxy }}
#          python-version: '3.11.3'
      - name: Build the RPM package
        run: |
          fpm -s dir -t rpm -n ${{ env.binary-basename }} \
            -v ${{ steps.package-versions.outputs.rpm }} \
            --iteration ${GITHUB_RUN_NUMBER} \
            --description "VoterWarehouse: Imports and Extracts Voter and History data" \
            --url "https://github.com/JamesJonesConsulting/VoterWarehouse" \
            --license "LGPL-3.0" --vendor "James Jones" --maintainer "James Jones <jamjon3@gmail.com>" \
            --config-files /etc/VoterWarehouse/config.yml \
            -p ./dist \
            ./dist/${{ env.binary-basename }}=/usr/bin/${{ env.binary-basename }} \
            ./config.sample.yml=/etc/VoterWarehouse/config.yml
          PACKAGE_FILE=$(find . -type f -name "${{ env.binary-basename }}*.rpm")
          rpm --import https://nexus.jamesjonesconsulting.com/repository/gpg/RPM-GPG-KEY-JAMJON3
          echo "${{ secrets.JAMJON3_RPM_SIGN_GPG_KEY }}" | base64 -d > key.gpg
          echo "${{ secrets.JAMJON3_RPM_SIGN_GPG_SECRET_KEY }}" | base64 -d > private.gpg
          export GPG_TTY=$(tty)
          gpg --import key.gpg
          echo '${{ secrets.JAMJON3_RPM_SIGN_PASSPHRASE }}' | gpg --batch --import private.gpg
          rpm --define "_gpg_name James Jones <jamjon3@gmail.com>" \
            --define "_gpg_sign_cmd_extra_args --pinentry-mode loopback --passphrase ${{ secrets.JAMJON3_RPM_SIGN_PASSPHRASE }}" \
            --addsign $PACKAGE_FILE
          if [[ "$GITHUB_REF" =~ ^refs/tags.* ]]; then
            curl -u "$YUM_USER:$YUM_PASSWORD" --upload-file $PACKAGE_FILE $NEXUS_YUM_REPO
            # package_cloud push $PACKAGE_CLOUD_REPO $PACKAGE_FILE
          fi
        shell: bash
        env:
          PACKAGE_CLOUD_REPO: jamjon3/yum/rpm_any/rpm_any
          YUM_USER: ${{ secrets.HOME_NEXUS_YUM_USER }}
          YUM_PASSWORD: ${{ secrets.HOME_NEXUS_YUM_PASSWORD }}
          NEXUS_YUM_REPO: https://nexus.jamesjonesconsulting.com/repository/yum-hosted/voting/
      - name: Build the DEB package
        run: |
          fpm -s dir -t deb -n ${{ env.binary-basename }} \
            -v ${{ steps.package-versions.outputs.deb }} \
            --iteration ${GITHUB_RUN_NUMBER} \
            --description "VoterWarehouse: Imports and Extracts Voter and History data" \
            --url "https://github.com/jamjon3/VoterWarehouse" \
            --license "LGPL-3.0" --vendor "James Jones" \
            --config-files /etc/VoterWarehouse/config.yml \
            -p ./dist \
            ./dist/${{ env.binary-basename }}=/usr/bin/${{ env.binary-basename }} \
            ./config.sample.yml=/etc/VoterWarehouse/config.yml
          echo "${{ secrets.JAMJON3_RPM_SIGN_GPG_KEY }}" | base64 -d > dist/key.gpg
          echo "${{ secrets.JAMJON3_RPM_SIGN_GPG_SECRET_KEY }}" | base64 -d > dist/private.gpg
          podman build --no-cache \
            --build-arg PRIVATE_KEY_PASS=${{ secrets.JAMJON3_RPM_SIGN_PASSPHRASE }} \
            --build-arg REGISTRY_PROXY=${{ env.registry-proxy }} \
            -f Dockerfile.ubuntu \
            -v "$(pwd)/dist:/dist:Z" .
          PACKAGE_FILE=$(find . -type f -name "${{ env.binary-basename }}*.deb")          
          if [[ "$GITHUB_REF" =~ ^refs/tags.* ]]; then
            apt_repos=(
              apt-focal-hosted
            )
            for repo in ${apt_repos[@]}; do
              DATA_BINARY='@'
              DATA_BINARY+="$PACKAGE_FILE"
              echo "$DATA_BINARY"
              echo "${NEXUS_APT_REPOSITORY_ROOT}${repo}/"
              curl -u "${APT_USER}:${APT_PASSWORD}" \
                -H "Content-Type: multipart/form-data" \
                --data-binary "${DATA_BINARY}" "${NEXUS_APT_REPOSITORY_ROOT}${repo}/"
            done
            # package_cloud push $PACKAGE_CLOUD_REPO $PACKAGE_FILE
          fi
        shell: bash
        env:
          PACKAGE_CLOUD_REPO: jamjon3/deb/any/any
          APT_USER: ${{ secrets.HOME_NEXUS_APT_USER }}
          APT_PASSWORD: ${{ secrets.HOME_NEXUS_APT_PASSWORD }}
          NEXUS_APT_REPOSITORY_ROOT: https://nexus.jamesjonesconsulting.com/repository/
      - name: Copy the new Windows executable into the tools folder
        run: |
          cd dist
          rm -f ../tools/*.exe
          cp "${{ env.binary-basename }}.exe" ../tools
      - name: Chocolatey Action
        uses: crazy-max/ghaction-chocolatey@v2.2.0
        with:
          args: pack --version ${{ steps.package-versions.outputs.nuget }} --outputdirectory dist
      - name: Publish Chocolatey package to hosted Chocolatey repo on Nexus
        if: ${{ startsWith(github.ref,'refs/tags/') }}
        run: |
          PACKAGE_FILE=$(find . -type f -name "*.nupkg")
          dotnet nuget push "${PACKAGE_FILE}" \
            -k ${{ secrets.HOME_NEXUS_NUGET_API_KEY }} \
            -s ${{ vars.HOME_NEXUS_NUGET_HOSTED_REPO }}
      - name: Create Zip Archives of the Linux/Windows CLI
        run: |
          cd dist
          zip -rm "${{ env.binary-basename }}-${{ steps.package-versions.outputs.standard }}-linux-x86_64.zip" "${{ env.binary-basename }}"
          zip -rm "${{ env.binary-basename }}-${{ steps.package-versions.outputs.standard }}-windows-x86_64.zip" "${{ env.binary-basename }}.exe"
      - name: Archive tool artifacts
        if: ${{ !startsWith(github.ref,'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.binary-basename }}-${{ steps.package-versions.outputs.standard }}"
          path: |
            dist
      - name: Release tool artifacts
        if: ${{ startsWith(github.ref,'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.*"
          allowUpdates: true
