name: Build VoterWarehouse
on: push
env:
  VERSION: 1.0.0
  ITERATION: 1
#  VERSION: $GITHUB_REF_NAME
#  ITERATION: $GITHUB_JOB

jobs:
  build-job:
    runs-on: self-hosted
    container:
      image: registry.fedoraproject.org/fedora:latest
      options: --userns=keep-id --privileged --user root
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Sets up RPM build tools and Ruby Gems
      - name: Install RPM dependencies
        run: dnf install -y rpm-build rpm-sign rubygems ruby-devel gcc gcc-c++ make libffi-devel python3
      # Sets up Rubygems packaging
      - name: Setup FPM with it's dependent package for building a package
        run: |
          gem install ffi
          gem install fpm
          gem install package_cloud
          echo $PC_TOKEN | base64 -d > $HOME/.packagecloud
        env:
          PC_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      # Sets up the python virtual environment, pulls the requirements and builds the binary
      - name: Build the binary
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install -r requirements.txt
          python build.py
      - name: Build the RPM package
        run: |
          fpm -s dir -t rpm -n voterwarehouse -v ${VERSION} --iteration ${ITERATION} \
          --description "VoterWarehouse: Imports and Extracts Voter and History data" \
          --url "https://github.com/jamjon3/VoterWarehouse" \
          --license "LGPL-3.0" --vendor "James Jones" \
          --config-files /etc/VoterWarehouse/config.yml \
          -p dist \
          ./dist/voterwarehouse=/usr/bin/voterwarehouse \
          ./config.sample.yml=/etc/VoterWarehouse/config.yml
          PACKAGE_FILE=$(find . -type f -name "voterwarehouse*.rpm")
          package_cloud push $PACKAGE_CLOUD_REPO $PACKAGE_FILE
        env:
          PACKAGE_CLOUD_REPO: jamjon3/yum
      - name: Build the DEB package
        run: |
          fpm -s dir -t deb -n voterwarehouse -v ${VERSION} --iteration ${ITERATION} \
          --description "VoterWarehouse: Imports and Extracts Voter and History data" \
          --url "https://github.com/jamjon3/VoterWarehouse" \
          --license "LGPL-3.0" --vendor "James Jones" \
          --config-files /etc/VoterWarehouse/config.yml \
          -p dist \
          ./dist/voterwarehouse=/usr/bin/voterwarehouse \
          ./config.sample.yml=/etc/VoterWarehouse/config.yml
          PACKAGE_FILE=$(find . -type f -name "voterwarehouse*.deb")
          package_cloud push $PACKAGE_CLOUD_REPO $PACKAGE_FILE
        env:
          PACKAGE_CLOUD_REPO: jamjon3/consulting
    
